# Generated by Django 3.2.6 on 2021-08-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stocks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modify', models.DateField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('symbol', models.CharField(max_length=8, verbose_name='Symbol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
